networks:
  external-network:
    name: external-network
    external: true

volumes:
  mssql-db-data:
    name: mssql-db-data
    
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    restart: always
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "${DATABASE_PORT}:1433"
    volumes:
      - mssql-db-data:/var/opt/mssql
    networks:
      - acc-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DATABASE_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: mssql-init
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - acc-network
    entrypoint: >
      /bin/bash -c '
      /opt/mssql-tools/bin/sqlcmd -S tcp:mssql-container,1433 -U sa -P "${DATABASE_PASSWORD}" -C -Q "CREATE DATABASE $DATABASE_NAME;"
      '
